root: true

env:
    browser: true
    es2021: true

extends: eslint:recommended

parserOptions:
    ecmaVersion: latest

rules:
    indent:
        - error
        - tab
        - SwitchCase: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
        - allowTemplateLiterals: true
    semi:
        - warn
        - never
    no-unused-vars:
    - error
    - vars: local
    no-constant-binary-expression: warn
    no-constructor-return: warn